// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssociateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemUuid        string                 `protobuf:"bytes,1,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	IngredientUuids []string               `protobuf:"bytes,2,rep,name=ingredient_uuids,json=ingredientUuids,proto3" json:"ingredient_uuids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssociateRequest) Reset() {
	*x = AssociateRequest{}
	mi := &file_proto_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateRequest) ProtoMessage() {}

func (x *AssociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateRequest.ProtoReflect.Descriptor instead.
func (*AssociateRequest) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{0}
}

func (x *AssociateRequest) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

func (x *AssociateRequest) GetIngredientUuids() []string {
	if x != nil {
		return x.IngredientUuids
	}
	return nil
}

type AssociateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateResponse) Reset() {
	*x = AssociateResponse{}
	mi := &file_proto_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateResponse) ProtoMessage() {}

func (x *AssociateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateResponse.ProtoReflect.Descriptor instead.
func (*AssociateResponse) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{1}
}

func (x *AssociateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssociateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetIngredientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuid      string                 `protobuf:"bytes,1,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientsRequest) Reset() {
	*x = GetIngredientsRequest{}
	mi := &file_proto_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientsRequest) ProtoMessage() {}

func (x *GetIngredientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientsRequest.ProtoReflect.Descriptor instead.
func (*GetIngredientsRequest) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{2}
}

func (x *GetIngredientsRequest) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

type GetIngredientsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IngredientUuids []string               `protobuf:"bytes,1,rep,name=ingredient_uuids,json=ingredientUuids,proto3" json:"ingredient_uuids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetIngredientsResponse) Reset() {
	*x = GetIngredientsResponse{}
	mi := &file_proto_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientsResponse) ProtoMessage() {}

func (x *GetIngredientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientsResponse.ProtoReflect.Descriptor instead.
func (*GetIngredientsResponse) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{3}
}

func (x *GetIngredientsResponse) GetIngredientUuids() []string {
	if x != nil {
		return x.IngredientUuids
	}
	return nil
}

type GetItemsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IngredientUuid string                 `protobuf:"bytes,1,opt,name=ingredient_uuid,json=ingredientUuid,proto3" json:"ingredient_uuid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_proto_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsRequest) GetIngredientUuid() string {
	if x != nil {
		return x.IngredientUuid
	}
	return ""
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuids     []string               `protobuf:"bytes,1,rep,name=item_uuids,json=itemUuids,proto3" json:"item_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_proto_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemsResponse) GetItemUuids() []string {
	if x != nil {
		return x.ItemUuids
	}
	return nil
}

type RemoveAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuid      string                 `protobuf:"bytes,1,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllRequest) Reset() {
	*x = RemoveAllRequest{}
	mi := &file_proto_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllRequest) ProtoMessage() {}

func (x *RemoveAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveAllRequest) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

type RemoveAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllResponse) Reset() {
	*x = RemoveAllResponse{}
	mi := &file_proto_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllResponse) ProtoMessage() {}

func (x *RemoveAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_relation_proto protoreflect.FileDescriptor

const file_proto_relation_proto_rawDesc = "" +
	"\n" +
	"\x14proto/relation.proto\x12\brelation\"Z\n" +
	"\x10AssociateRequest\x12\x1b\n" +
	"\titem_uuid\x18\x01 \x01(\tR\bitemUuid\x12)\n" +
	"\x10ingredient_uuids\x18\x02 \x03(\tR\x0fingredientUuids\"G\n" +
	"\x11AssociateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x15GetIngredientsRequest\x12\x1b\n" +
	"\titem_uuid\x18\x01 \x01(\tR\bitemUuid\"C\n" +
	"\x16GetIngredientsResponse\x12)\n" +
	"\x10ingredient_uuids\x18\x01 \x03(\tR\x0fingredientUuids\":\n" +
	"\x0fGetItemsRequest\x12'\n" +
	"\x0fingredient_uuid\x18\x01 \x01(\tR\x0eingredientUuid\"1\n" +
	"\x10GetItemsResponse\x12\x1d\n" +
	"\n" +
	"item_uuids\x18\x01 \x03(\tR\titemUuids\"/\n" +
	"\x10RemoveAllRequest\x12\x1b\n" +
	"\titem_uuid\x18\x01 \x01(\tR\bitemUuid\"-\n" +
	"\x11RemoveAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe5\x02\n" +
	"\x0fRelationService\x12O\n" +
	"\x14AssociateIngredients\x12\x1a.relation.AssociateRequest\x1a\x1b.relation.AssociateResponse\x12Y\n" +
	"\x14GetIngredientsByItem\x12\x1f.relation.GetIngredientsRequest\x1a .relation.GetIngredientsResponse\x12M\n" +
	"\x14GetItemsByIngredient\x12\x19.relation.GetItemsRequest\x1a\x1a.relation.GetItemsResponse\x12W\n" +
	"\x1cRemoveAllAssociationsForItem\x12\x1a.relation.RemoveAllRequest\x1a\x1b.relation.RemoveAllResponseB\x0fZ\rbackend/pb;pbb\x06proto3"

var (
	file_proto_relation_proto_rawDescOnce sync.Once
	file_proto_relation_proto_rawDescData []byte
)

func file_proto_relation_proto_rawDescGZIP() []byte {
	file_proto_relation_proto_rawDescOnce.Do(func() {
		file_proto_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_relation_proto_rawDesc), len(file_proto_relation_proto_rawDesc)))
	})
	return file_proto_relation_proto_rawDescData
}

var file_proto_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_relation_proto_goTypes = []any{
	(*AssociateRequest)(nil),       // 0: relation.AssociateRequest
	(*AssociateResponse)(nil),      // 1: relation.AssociateResponse
	(*GetIngredientsRequest)(nil),  // 2: relation.GetIngredientsRequest
	(*GetIngredientsResponse)(nil), // 3: relation.GetIngredientsResponse
	(*GetItemsRequest)(nil),        // 4: relation.GetItemsRequest
	(*GetItemsResponse)(nil),       // 5: relation.GetItemsResponse
	(*RemoveAllRequest)(nil),       // 6: relation.RemoveAllRequest
	(*RemoveAllResponse)(nil),      // 7: relation.RemoveAllResponse
}
var file_proto_relation_proto_depIdxs = []int32{
	0, // 0: relation.RelationService.AssociateIngredients:input_type -> relation.AssociateRequest
	2, // 1: relation.RelationService.GetIngredientsByItem:input_type -> relation.GetIngredientsRequest
	4, // 2: relation.RelationService.GetItemsByIngredient:input_type -> relation.GetItemsRequest
	6, // 3: relation.RelationService.RemoveAllAssociationsForItem:input_type -> relation.RemoveAllRequest
	1, // 4: relation.RelationService.AssociateIngredients:output_type -> relation.AssociateResponse
	3, // 5: relation.RelationService.GetIngredientsByItem:output_type -> relation.GetIngredientsResponse
	5, // 6: relation.RelationService.GetItemsByIngredient:output_type -> relation.GetItemsResponse
	7, // 7: relation.RelationService.RemoveAllAssociationsForItem:output_type -> relation.RemoveAllResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_relation_proto_init() }
func file_proto_relation_proto_init() {
	if File_proto_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_relation_proto_rawDesc), len(file_proto_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_relation_proto_goTypes,
		DependencyIndexes: file_proto_relation_proto_depIdxs,
		MessageInfos:      file_proto_relation_proto_msgTypes,
	}.Build()
	File_proto_relation_proto = out.File
	file_proto_relation_proto_goTypes = nil
	file_proto_relation_proto_depIdxs = nil
}
