// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/relation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelationService_AssociateIngredients_FullMethodName         = "/relation.RelationService/AssociateIngredients"
	RelationService_GetIngredientsByItem_FullMethodName         = "/relation.RelationService/GetIngredientsByItem"
	RelationService_GetItemsByIngredient_FullMethodName         = "/relation.RelationService/GetItemsByIngredient"
	RelationService_RemoveAllAssociationsForItem_FullMethodName = "/relation.RelationService/RemoveAllAssociationsForItem"
)

// RelationServiceClient is the client API for RelationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelationServiceClient interface {
	AssociateIngredients(ctx context.Context, in *AssociateRequest, opts ...grpc.CallOption) (*AssociateResponse, error)
	GetIngredientsByItem(ctx context.Context, in *GetIngredientsRequest, opts ...grpc.CallOption) (*GetIngredientsResponse, error)
	GetItemsByIngredient(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error)
	RemoveAllAssociationsForItem(ctx context.Context, in *RemoveAllRequest, opts ...grpc.CallOption) (*RemoveAllResponse, error)
}

type relationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelationServiceClient(cc grpc.ClientConnInterface) RelationServiceClient {
	return &relationServiceClient{cc}
}

func (c *relationServiceClient) AssociateIngredients(ctx context.Context, in *AssociateRequest, opts ...grpc.CallOption) (*AssociateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssociateResponse)
	err := c.cc.Invoke(ctx, RelationService_AssociateIngredients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationServiceClient) GetIngredientsByItem(ctx context.Context, in *GetIngredientsRequest, opts ...grpc.CallOption) (*GetIngredientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIngredientsResponse)
	err := c.cc.Invoke(ctx, RelationService_GetIngredientsByItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationServiceClient) GetItemsByIngredient(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsResponse)
	err := c.cc.Invoke(ctx, RelationService_GetItemsByIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationServiceClient) RemoveAllAssociationsForItem(ctx context.Context, in *RemoveAllRequest, opts ...grpc.CallOption) (*RemoveAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAllResponse)
	err := c.cc.Invoke(ctx, RelationService_RemoveAllAssociationsForItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelationServiceServer is the server API for RelationService service.
// All implementations must embed UnimplementedRelationServiceServer
// for forward compatibility.
type RelationServiceServer interface {
	AssociateIngredients(context.Context, *AssociateRequest) (*AssociateResponse, error)
	GetIngredientsByItem(context.Context, *GetIngredientsRequest) (*GetIngredientsResponse, error)
	GetItemsByIngredient(context.Context, *GetItemsRequest) (*GetItemsResponse, error)
	RemoveAllAssociationsForItem(context.Context, *RemoveAllRequest) (*RemoveAllResponse, error)
	mustEmbedUnimplementedRelationServiceServer()
}

// UnimplementedRelationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelationServiceServer struct{}

func (UnimplementedRelationServiceServer) AssociateIngredients(context.Context, *AssociateRequest) (*AssociateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssociateIngredients not implemented")
}
func (UnimplementedRelationServiceServer) GetIngredientsByItem(context.Context, *GetIngredientsRequest) (*GetIngredientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngredientsByItem not implemented")
}
func (UnimplementedRelationServiceServer) GetItemsByIngredient(context.Context, *GetItemsRequest) (*GetItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItemsByIngredient not implemented")
}
func (UnimplementedRelationServiceServer) RemoveAllAssociationsForItem(context.Context, *RemoveAllRequest) (*RemoveAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAllAssociationsForItem not implemented")
}
func (UnimplementedRelationServiceServer) mustEmbedUnimplementedRelationServiceServer() {}
func (UnimplementedRelationServiceServer) testEmbeddedByValue()                         {}

// UnsafeRelationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelationServiceServer will
// result in compilation errors.
type UnsafeRelationServiceServer interface {
	mustEmbedUnimplementedRelationServiceServer()
}

func RegisterRelationServiceServer(s grpc.ServiceRegistrar, srv RelationServiceServer) {
	// If the following call panics, it indicates UnimplementedRelationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelationService_ServiceDesc, srv)
}

func _RelationService_AssociateIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssociateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).AssociateIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationService_AssociateIngredients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).AssociateIngredients(ctx, req.(*AssociateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationService_GetIngredientsByItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngredientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).GetIngredientsByItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationService_GetIngredientsByItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).GetIngredientsByItem(ctx, req.(*GetIngredientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationService_GetItemsByIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).GetItemsByIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationService_GetItemsByIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).GetItemsByIngredient(ctx, req.(*GetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationService_RemoveAllAssociationsForItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).RemoveAllAssociationsForItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationService_RemoveAllAssociationsForItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).RemoveAllAssociationsForItem(ctx, req.(*RemoveAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelationService_ServiceDesc is the grpc.ServiceDesc for RelationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relation.RelationService",
	HandlerType: (*RelationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssociateIngredients",
			Handler:    _RelationService_AssociateIngredients_Handler,
		},
		{
			MethodName: "GetIngredientsByItem",
			Handler:    _RelationService_GetIngredientsByItem_Handler,
		},
		{
			MethodName: "GetItemsByIngredient",
			Handler:    _RelationService_GetItemsByIngredient_Handler,
		},
		{
			MethodName: "RemoveAllAssociationsForItem",
			Handler:    _RelationService_RemoveAllAssociationsForItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/relation.proto",
}
